VIT 21 training webform
ManatiCR/vitaminau pull request #66
Opened 2020-09-15 22:32 UTC by valevas6

2020-09-16 20:31 UTC, randallquesadaa commented
Hello Valeria, the document and the form have these differences:
- Date: The document asks for the month and year, the form contains the year, date and day.
- Other: The field is required in the document and it is not in the form (ask about this).

2020-09-23 02:12 UTC, dharizza requested changes
Some things are still missing:
- In the field "Beneficiarios" when user selects the option "Comunidad" in "Tipo de beneficiario" there should appear the checkboxes for "Provincia" (which is there) and the long text field "Detalle comunidad" (which is not there), please add it. Look at other forms to confirm, it should look like this: 
![image](https://user-images.githubusercontent.com/2200763/93956421-68095400-fd0f-11ea-9d85-4e2baa592f08.png)
- Please look into all the composite fields, the labels for the +/- buttons are not present, right now it looks like this: 
![image](https://user-images.githubusercontent.com/2200763/93956484-9129e480-fd0f-11ea-9d71-7d0619db00cd.png)
when it should look like this: 
![image](https://user-images.githubusercontent.com/2200763/93956527-a69f0e80-fd0f-11ea-82e8-c96457ceddcc.png)
- Remove the "No encuentro mi código de proyecto en la lista" node from Capacitaciones as it was created manually in prod, use that instead. The fields for "Código específico de mi proyecto" and "Unidad específica" are not shown when they should, please use the newest db backup and use the right reference to the node created in production.

2020-09-23 02:12 UTC, dharizza commented on content/node/95f0cc87-28aa-4d4b-8f38-73f41a650640.json
> +{
Please remove this, I created the node in production directly. Use that and update the conditions for showing the "Código específico de mi proyecto" and "Unidad específica" fields.

2020-09-25 13:39 UTC, dharizza approved these changes

2020-09-25 13:54 UTC, merged