VIT-24 expert services form
ManatiCR/vitaminau pull request #80
Opened 2020-09-18 15:27 UTC by jsteven97

# Task [VIT-24](https://manati.atlassian.net/secure/RapidBoard.jspa?rapidView=104&projectKey=VIT&modal=detail&selectedIssue=VIT-24)
Service expert Webform

## Installation 
_If you dont have migration you will need to run:_
- [ ] ahoy composer install
- [ ] ahoy drush en vitaminau_migrations
- [ ] ahoy drush ms
- [ ] ahoy drush migrate-import vitaminau_migration_careers
- [ ] ahoy drush migrate-import vitaminau_migration_cultural_project
- [ ] ahoy drush migrate-import vitaminau_migration_expert_service
- [ ] ahoy drush migrate-import vitaminau_migration_unit

**RUN:**
- [ ] ahoy drush cim -y && ahoy drush cr
- [ ] ahoy drush dcdi

**- Check [descriptions](https://docs.google.com/spreadsheets/d/1g4bC1rd_48hHrhUQYUrL_A7Xa9Pc4C5U7gqaI5eaw6M/edit#gid=276324474)**

## Test
- Go to [Training form](http://vitaminau.docker/formularios/servicios-expertos).
- Verify beneficiaries section works correctly. 

## CA
- The webform has the requirement fields, if someone doesn't field it the form will be not send.
- You will see in the list of forms the training form.
- You can save drafts. 
- The draft preload correctly.
- The form is visible only authenticated users.
- If you don't select a code you cant send the form.
- The info automatically filled if you select a code.
- The last options is "I don't found mi code in the list"
- If you select  "I don't found mi code in the list" the unit change to a select with all the options.

2020-09-18 16:03 UTC, valevas6 commented
Compound fields do not look good, they are seen in several columns it should be only one per field.
The node is not exported with the dcdi.
In the composite "Experto" the label "Correo" needs to be "Correo institucional"
Beneficiaries part doesn't work, it doe not open any option if I select for example "Comunidad"
The config in "Código de proyecto de investigación vigente" it's not correct, you need to create a node and delete the select option there. Also the field needs to be required.

2020-09-22 13:32 UTC, valevas6 commented
We don't need to put in the PR the migrations because when you install the site, the migrations are alredy on the site.
Add the option "todos" in the beneficiaries part.
When you choose "no encuentro mi unidad" a new field text needs to appear for write the specific unit.

2020-09-25 13:53 UTC, dharizza requested changes
This looks good, though the first field for beneficiaries in this form is not showing correctly the help text for counties, look: 
![image](https://user-images.githubusercontent.com/2200763/94275457-39080380-ff04-11ea-84a1-334998e2112b.png)
Please fix.

2020-09-25 19:45 UTC, dharizza approved these changes

2020-09-25 19:46 UTC, merged